#!/usr/bin/env python3
"""Read every results/bench/<host>.md and emit results/bench/comparison.md.

Each host file is the markdown emitted by scripts/bench_remote_control.py.
Comparison output is a single iPhone-friendly markdown table (4 narrow
columns: metric | host1 | host2 | delta%) that GitHub renders cleanly on
mobile.

Hosts are sorted by aggregate score descending (fastest first). When more
than 2 hosts are present, every host gets a column and the rightmost
delta is "best-vs-worst %".

Usage: python3 scripts/bench_compare.py [--out results/bench/comparison.md]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BENCH_DIR = ROOT / "results" / "bench"

ROW_RE = re.compile(r"^\|\s*(?P<metric>[\w.\-/]+(?:\s+\([^)]+\))?)\s*\|"
                    r"\s*(?P<value>[\w,\.\-:%]+|TIMEOUT)\s*\|"
                    r"\s*(?P<unit>[^|]+?)\s*\|\s*$")
SCORE_RE = re.compile(r"^`([\d,]+)`\s*$")


def parse_host_file(fp: Path) -> dict:
    """Extract host metadata + metric rows from one bench output file."""
    out: dict = {"host_file": fp.name, "host": fp.stem, "metrics": {}, "score": None,
                 "host_meta": {}}
    if not fp.exists():
        return out
    text = fp.read_text()

    # Host metadata lines: support both backtick-wrapped values
    #   "- host:     `ValsSpectre`"
    # and plain key=value:
    #   "- RAM:      total=7.6 GB  available=6.0 GB"
    for line in text.splitlines():
        if not line.startswith("- "):
            continue
        m = re.match(r"^- (\S+?):\s+`([^`]+)`\s*$", line)
        if m:
            out["host_meta"][m.group(1)] = m.group(2)
            continue
        m = re.match(r"^- (\S+?):\s+(.+?)\s*$", line)
        if m:
            out["host_meta"][m.group(1)] = m.group(2)

    # Override host name from "- host:" line if present (matches hostname tool)
    if out["host_meta"].get("host"):
        out["host"] = out["host_meta"]["host"]

    # Metric rows
    for line in text.splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        metric = m.group("metric").strip()
        if metric == "metric":
            continue  # header
        value_raw = m.group("value").strip()
        unit = m.group("unit").strip()

        if value_raw == "TIMEOUT":
            out["metrics"][metric] = (None, unit)
            continue
        # Strip commas, parse float
        try:
            v = float(value_raw.replace(",", ""))
        except ValueError:
            continue
        out["metrics"][metric] = (v, unit)

    # Score
    after_score = False
    for line in text.splitlines():
        if line.startswith("## Aggregate score"):
            after_score = True
            continue
        if after_score:
            ms = SCORE_RE.match(line.strip())
            if ms:
                out["score"] = float(ms.group(1).replace(",", ""))
                break
    return out


def format_value(v: float | None, unit: str) -> str:
    if v is None:
        return "TIMEOUT"
    if v >= 1_000_000:
        return f"{v/1_000_000:.1f}M"
    if v >= 1000:
        return f"{v:,.0f}"
    if v >= 10:
        return f"{v:,.1f}"
    return f"{v:.3f}"


def fmt_delta_pct(best: float, worst: float, unit: str) -> str:
    """Δ% best vs worst. For latency units, smaller is better. Show signed."""
    if best is None or worst is None or worst == 0:
        return ""
    latency = unit.startswith("ms")
    if latency:
        # smaller is better -- delta is how much SLOWER worst is than best
        d = 100 * (worst - best) / best
        return f"+{d:.0f}%"
    else:
        d = 100 * (best - worst) / worst
        return f"+{d:.0f}%"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, default=BENCH_DIR / "comparison.md")
    args = p.parse_args()

    BENCH_DIR.mkdir(parents=True, exist_ok=True)
    files = sorted(f for f in BENCH_DIR.glob("*.md")
                   if f.name != "comparison.md" and f.name != "README.md")
    if not files:
        print(f"No bench files in {BENCH_DIR}", file=sys.stderr)
        return 1

    hosts = [parse_host_file(f) for f in files]
    # Sort by aggregate score desc (fastest first); None → end
    hosts.sort(key=lambda h: (-(h["score"] or -1)))

    # Union of all metric names, preserving the order from the first host
    seen_order = list(hosts[0]["metrics"].keys()) if hosts else []
    for h in hosts[1:]:
        for k in h["metrics"]:
            if k not in seen_order:
                seen_order.append(k)

    # ----- build markdown -----
    lines = []
    lines.append("# Cross-machine benchmark comparison")
    lines.append("")
    lines.append(f"Generated by `scripts/bench_compare.py` from "
                 f"{len(hosts)} host result file(s).")
    lines.append("")

    # Host index
    lines.append("## Hosts")
    lines.append("")
    lines.append("| # | hostname | CPU | RAM | score |")
    lines.append("|---|---|---|---|---:|")
    for i, h in enumerate(hosts, 1):
        meta = h["host_meta"]
        cpu = meta.get("CPU", "?")
        if len(cpu) > 60:
            cpu = cpu[:57] + "..."
        ram = meta.get("RAM", "?").split("available")[0].replace("total=", "").strip()
        s = f"{h['score']:,.0f}" if h["score"] else "?"
        lines.append(f"| **{i}** | `{h['host']}` | {cpu} | {ram} | {s} |")
    lines.append("")

    # Side-by-side metrics
    lines.append("## Per-metric comparison")
    lines.append("")

    header = ["metric"]
    for i, h in enumerate(hosts, 1):
        header.append(f"#{i} {h['host']}")
    header.append("unit")
    if len(hosts) >= 2:
        header.append("Δ%")
    lines.append("| " + " | ".join(header) + " |")
    sep = ["---"] + ["---:" for _ in hosts] + ["---"]
    if len(hosts) >= 2:
        sep.append("---:")
    lines.append("|" + "|".join(sep) + "|")

    for metric in seen_order:
        row = [metric]
        values = []
        unit = ""
        for h in hosts:
            v, u = h["metrics"].get(metric, (None, ""))
            values.append(v)
            if u:
                unit = u
            row.append(format_value(v, u))
        row.append(unit)
        if len(hosts) >= 2:
            valid = [v for v in values if v is not None]
            if len(valid) >= 2:
                if unit.startswith("ms"):
                    best, worst = min(valid), max(valid)
                else:
                    best, worst = max(valid), min(valid)
                row.append(fmt_delta_pct(best, worst, unit))
            else:
                row.append("")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append("> Δ% = best-vs-worst gap (higher = bigger spread). "
                 "Latency rows (ms) treat lower as better; throughput rows "
                 "(MB/s, IOPS, ops/s, tasks/s) treat higher as better.")

    output = "\n".join(lines) + "\n"
    args.out.write_text(output)
    print(f"Wrote {args.out} ({len(output)} chars, {len(hosts)} hosts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
