"""Hardcoded earnings calendar -- generated by orb_earnings_fetcher.py."""

# Last refreshed: 2026-05-12 14:11 UTC

EARNINGS_CALENDAR: dict[str, list[tuple[str, str]]] = {
    "AAPL": [],
    "MSFT": [],
    "NVDA": [],
    "TSLA": [],
    "META": [],
    "GOOG": [],
    "AMZN": [],
    "AVGO": [],
    "NFLX": [],
    "ORCL": [],
    "SPY": [],
    "QQQ": [],
}



def is_earnings_window(ticker: str, date: str, days_before: int = 1,
                       days_after: int = 0) -> bool:
    """Return True if `date` falls within an earnings-blackout window."""
    from datetime import date as _date, timedelta
    sched = EARNINGS_CALENDAR.get(ticker, [])
    if not sched:
        return False
    try:
        d = _date.fromisoformat(date)
    except ValueError:
        return False
    for ed_str, _when in sched:
        try:
            ed = _date.fromisoformat(ed_str)
        except ValueError:
            continue
        window_start = ed - timedelta(days=days_before)
        window_end = ed + timedelta(days=days_after)
        if window_start <= d <= window_end:
            return True
    return False
