"""Hardcoded earnings calendar -- generated by orb_earnings_fetcher.py."""

# Last refreshed: 2026-05-19 14:51 UTC

EARNINGS_CALENDAR: dict[str, list[tuple[str, str]]] = {
    "AAPL": [("2024-10-31", "AMC"), ("2025-01-30", "AMC"), ("2025-05-01", "AMC"), ("2025-07-31", "AMC"), ("2025-10-30", "AMC"), ("2026-01-29", "AMC"), ("2026-04-30", "AMC")],
    "MSFT": [("2024-10-30", "AMC"), ("2025-01-29", "AMC"), ("2025-04-30", "AMC"), ("2025-07-30", "AMC"), ("2025-10-29", "AMC"), ("2026-01-28", "AMC"), ("2026-04-29", "AMC")],
    "NVDA": [("2024-11-20", "AMC"), ("2025-02-26", "AMC"), ("2025-05-28", "AMC"), ("2025-08-27", "AMC"), ("2025-11-19", "AMC"), ("2026-02-25", "AMC"), ("2026-05-20", "AMC")],
    "TSLA": [("2024-10-23", "AMC"), ("2025-01-29", "AMC"), ("2025-04-22", "AMC"), ("2025-07-23", "AMC"), ("2025-10-22", "AMC"), ("2026-01-28", "AMC"), ("2026-04-22", "AMC")],
    "META": [("2024-10-30", "AMC"), ("2025-01-29", "AMC"), ("2025-04-30", "AMC"), ("2025-07-30", "AMC"), ("2025-10-29", "AMC"), ("2026-01-28", "AMC"), ("2026-04-29", "AMC")],
    "GOOG": [("2024-10-29", "AMC"), ("2025-02-04", "AMC"), ("2025-04-24", "AMC"), ("2025-07-23", "AMC"), ("2025-10-29", "AMC"), ("2026-02-04", "AMC"), ("2026-04-29", "AMC")],
    "AMZN": [("2024-10-31", "AMC"), ("2025-02-06", "AMC"), ("2025-05-01", "AMC"), ("2025-07-31", "AMC"), ("2025-10-30", "AMC"), ("2026-02-05", "AMC"), ("2026-04-29", "AMC")],
    "AVGO": [("2024-12-12", "AMC"), ("2025-03-06", "AMC"), ("2025-06-05", "AMC"), ("2025-09-04", "AMC"), ("2025-12-11", "AMC"), ("2026-03-04", "AMC"), ("2026-06-03", "AMC")],
    "NFLX": [("2024-10-17", "AMC"), ("2025-01-21", "AMC"), ("2025-04-17", "AMC"), ("2025-07-17", "AMC"), ("2025-10-21", "AMC"), ("2026-01-20", "AMC"), ("2026-04-16", "AMC")],
    "ORCL": [("2024-12-09", "AMC"), ("2025-03-10", "AMC"), ("2025-06-11", "AMC"), ("2025-09-09", "AMC"), ("2025-12-10", "AMC"), ("2026-03-10", "AMC"), ("2026-06-10", "AMC")],
    "SPY": [],
    "QQQ": [],
}



def is_earnings_window(ticker: str, date: str, days_before: int = 1,
                       days_after: int = 0) -> bool:
    """Return True if `date` falls within an earnings-blackout window."""
    from datetime import date as _date, timedelta
    sched = EARNINGS_CALENDAR.get(ticker, [])
    if not sched:
        return False
    try:
        d = _date.fromisoformat(date)
    except ValueError:
        return False
    for ed_str, _when in sched:
        try:
            ed = _date.fromisoformat(ed_str)
        except ValueError:
            continue
        window_start = ed - timedelta(days=days_before)
        window_end = ed + timedelta(days=days_after)
        if window_start <= d <= window_end:
            return True
    return False
