"""Earnings calendar fetcher (live feed for production deployment).

This script runs OUTSIDE the sandbox (on user's local machine, on Railway,
or any environment with internet access to Yahoo Finance). It fetches
upcoming earnings dates for the v8/v9 12-ticker universe and writes the
result to `tools/orb_earnings_calendar.py` for the backtest + live engine
to consume.

Usage:
    python tools/orb_earnings_fetcher.py [--lookback-days 90] [--lookahead-days 90]

Quarterly refresh recommended. Re-run before each new earnings season
(typically January, April, July, October) to catch newly-announced dates.

Look-ahead audit (rule #7b): the fetcher is a STATIC schedule fetcher.
Earnings dates are public schedules announced weeks in advance. Using
them in a backtest does not introduce future information.

Dependencies (install on the host machine):
    pip install yfinance

Sandbox note: Yahoo Finance is sandbox-blocked in our backtest harness, so
this script will NOT run inside Claude Code sessions. It runs on the
user's machine where the result is committed back to the repo.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

UNIVERSE = ["AAPL", "MSFT", "NVDA", "TSLA", "META", "GOOG",
            "AMZN", "AVGO", "NFLX", "ORCL", "SPY", "QQQ"]


def fetch_earnings_dates(ticker: str, start: str, end: str) -> list[tuple[str, str]]:
    """Return [(YYYY-MM-DD, "AMC"|"BMO"), ...] for `ticker` in [start, end].

    Uses yfinance's `Ticker.earnings_dates` which returns a DataFrame
    with announce timestamps and an "Earnings Time" hint when available.
    """
    try:
        import yfinance as yf
    except ImportError:
        print("ERROR: yfinance not installed. Run: pip install yfinance",
              file=sys.stderr)
        sys.exit(2)
    try:
        t = yf.Ticker(ticker)
        df = t.earnings_dates
        if df is None or df.empty:
            return []
    except Exception as e:
        print(f"WARN {ticker}: {e}", file=sys.stderr)
        return []
    out = []
    for ts, row in df.iterrows():
        d = ts.strftime("%Y-%m-%d") if hasattr(ts, "strftime") else str(ts)[:10]
        if not (start <= d <= end):
            continue
        # yfinance "Earnings Time" hints: Time.AfterMarket / Time.BeforeMarket / Time.TimeNotSupplied
        when = "AMC"  # default assumption (most US large caps)
        time_hint = str(row.get("Earnings Time", "")) if hasattr(row, "get") else ""
        if "Before" in time_hint:
            when = "BMO"
        elif "After" in time_hint:
            when = "AMC"
        out.append((d, when))
    return out


def write_calendar(dates: dict[str, list[tuple[str, str]]], out_path: Path) -> None:
    """Write the calendar dict to a Python module that orb_backtest imports."""
    lines = ['"""Hardcoded earnings calendar -- generated by orb_earnings_fetcher.py."""',
             "",
             f"# Last refreshed: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
             "",
             "EARNINGS_CALENDAR: dict[str, list[tuple[str, str]]] = {"]
    for tk in UNIVERSE:
        events = dates.get(tk, [])
        # Sort by date
        events.sort()
        formatted = ", ".join(f'("{d}", "{w}")' for d, w in events)
        lines.append(f'    "{tk}": [{formatted}],')
    lines.append("}")
    lines.append("")
    # Append the helper function (copied from existing module to keep
    # signature stable)
    lines.append("""

def is_earnings_window(ticker: str, date: str, days_before: int = 1,
                       days_after: int = 0) -> bool:
    \"\"\"Return True if `date` falls within an earnings-blackout window.\"\"\"
    from datetime import date as _date, timedelta
    sched = EARNINGS_CALENDAR.get(ticker, [])
    if not sched:
        return False
    try:
        d = _date.fromisoformat(date)
    except ValueError:
        return False
    for ed_str, _when in sched:
        try:
            ed = _date.fromisoformat(ed_str)
        except ValueError:
            continue
        window_start = ed - timedelta(days=days_before)
        window_end = ed + timedelta(days=days_after)
        if window_start <= d <= window_end:
            return True
    return False
""")
    out_path.write_text("\n".join(lines))


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--lookback-days", type=int, default=90,
                   help="History window before today")
    p.add_argument("--lookahead-days", type=int, default=180,
                   help="Future window after today")
    p.add_argument("--out", default="tools/orb_earnings_calendar.py",
                   help="Output module path")
    args = p.parse_args(argv[1:])

    today = datetime.utcnow()
    start = (today - timedelta(days=args.lookback_days)).strftime("%Y-%m-%d")
    end = (today + timedelta(days=args.lookahead_days)).strftime("%Y-%m-%d")
    print(f"Fetching earnings for {len(UNIVERSE)} tickers, "
          f"window [{start}, {end}]...")

    dates: dict[str, list[tuple[str, str]]] = {}
    for tk in UNIVERSE:
        events = fetch_earnings_dates(tk, start, end)
        dates[tk] = events
        print(f"  {tk}: {len(events)} dates")

    out_path = Path(args.out)
    write_calendar(dates, out_path)
    total = sum(len(v) for v in dates.values())
    print(f"\nWrote {total} earnings events to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
